name: Express App Main Branch CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env: 
      CI: true
      MONGO_URL: mongodb://localhost/db-name
    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['4.4', '5.0', '6.0']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version}}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - run: npm install